Update config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -94,10 +94,10 @@ jobs:
             tailscale --socket=/tmp/tailscaled.sock ip -4 vlci01
 
             echo "nc"
-            nc -vz -w 3 $( tailscale --socket=/tmp/tailscaled.sock ip -4 vlci01 ) 443
+            nc -vz -w 3 $( tailscale --socket=/tmp/tailscaled.sock ip -4 vlci01 ) 443 || echo "error"
 
             echo "curl"
-            curl -L --connect-timeout 3 -v https://$( tailscale ip -4 vlci01 )
+            curl -L --connect-timeout 3 -v https://$( tailscale ip -4 vlci01 ) || echo "error"
 
 # Orchestrate jobs using workflows
 # See: https://circleci.com/docs/configuration-reference/#workflows
